apiVersion: v1
kind: Namespace
metadata:
  name: codeanalysis
  labels:
    name: codeanalysis
    app.kubernetes.io/name: codeanalysis-multiagent-mvp
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codeanalysis
  namespace: codeanalysis
  labels:
    app.kubernetes.io/name: codeanalysis-multiagent-mvp
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codeanalysis
  labels:
    app.kubernetes.io/name: codeanalysis-multiagent-mvp
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codeanalysis
  labels:
    app.kubernetes.io/name: codeanalysis-multiagent-mvp
subjects:
- kind: ServiceAccount
  name: codeanalysis
  namespace: codeanalysis
roleRef:
  kind: ClusterRole
  name: codeanalysis
  apiGroup: rbac.authorization.k8s.io